services:
  api:
    container_name: tech-challenge-api
    build:
      context: ./
      dockerfile: src/FIAP.TechChallenge.ByteMeBurger.Api/Dockerfile
      tags:
        - newwebapi
    restart: always
    networks:
      - tech-challenge
    ports:
      - 8080:8080
    environment:
      - MongoSettings__Username=${MONGO_USERNAME}
      - MongoSettings__Password=${MONGO_PASSWORD}
      - MongoSettings__Database=${MONGO_DATABASE}
      - MongoSettings__Port=${MONGO_PORT}

  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - tech-challenge
    ports:
      - 27017:27017

networks:
  tech-challenge:
    driver: bridge